repository:
  type: InMemory
  fallBackUrl: https://shorten.fifth-postulate.nl
  suggestionUrl: https://shorten.fifth-postulate.nl/

shortenstrategy:
  type: StoreBacked

couchdb:
  url: http://localhost:5984/shortener
  username: admin
  password: password
