http:
  timeout: 5000

repository:
  type: Store
  fallBackUrl: https://dvb.usef-dynamo.nl
  suggestionUrl: https://dvb.usef-dynamo.nl/

shortenstrategy:
  type: StoreBacked

couchdb:
  url: ${COUCHDB_URL}
  username: ${COUCHDB_USERNAME}
  password: ${COUCHDB_PASSWORD}
